services:
  - type: web
    name: bluedo-api
    env: node
    rootDir: server
    buildCommand: bash ./build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
